### ISSUE TITLE
Dataset Source

### ISSUE THREAD

**Issue by yssl0726** [Daniel-Arayala/RUL_estimation_paper_mill#1]
Hello, can you provide me with the source of the paper mill dataset?

**Comment by Daniel-Arayala** [comment]
@yssl0726 I just added the dataset article in the README.md file. You can also request access to that dataset through the form: https://docs.google.com/forms/d/e/1FAIpQLSdyUk3lfDl7I5KYK_pw285LCApc-_RcoC0Tf9cnDnZ_TWzPAw/viewform. The form link is on the last page of the article.
